
-- MYSQL;
---------------------------------------------------------------------------------------------------
CREATE TABLE NOME_TABELA (
id             INT         AUTO_INCREMENT PRIMARY KEY,
NOME_COLUNA_FK INT         NOT NULL,
NOME_COLUNA    VARCHAR(50) NOT NULL,
DATA_CRIACAO   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
DATA_ALTERACAO TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (NOME_COLUNA_FK) REFERENCES NOME_TABELA(NOME_COLUNA_FK)
);

-- ORACLE;
---------------------------------------------------------------------------------------------------
CREATE TABLE NOME_TABELA (
id             INT         PRIMARY KEY,
NOME_COLUNA_FK INT         NOT NULL,
NOME_COLUNA    VARCHAR(50) NOT NULL,
DATA_CRIACAO   TIMESTAMP   NOT NULL,
DATA_ALTERACAO TIMESTAMP   NOT NULL,
FOREIGN KEY (NOME_COLUNA_FK) REFERENCES NOME_TABELA(NOME_COLUNA_FK)
);
-- CREATE SEQUENCE NOME_TABELA_SEQ
-- START WITH 1;

-- SQL SERVER;
---------------------------------------------------------------------------------------------------
CREATE TABLE NOME_TABELA (
id             INT         IDENTITY PRIMARY KEY,
NOME_COLUNA_FK INT         NOT NULL,
NOME_COLUNA    VARCHAR(50) NOT NULL,
DATA_CRIACAO   DATETIME    NOT NULL,
DATA_ALTERACAO DATETIME    NOT NULL,
FOREIGN KEY (NOME_COLUNA_FK) REFERENCES NOME_TABELA(NOME_COLUNA_FK)
);
