-- ENCONTRA PROCESSOS OCIOSOS
SELECT 
	 PRC.COD_FORM
	,PRC.COD_PROCESSO
	,FRM.DES_TITULO
	,ETP.DES_ETAPA
	,PE.COD_USUARIO_ETAPA
	,USU.NOM_USUARIO
FROM PROCESSO AS PRC
INNER JOIN PROCESSO_ETAPA AS PE
ON PRC.COD_PROCESSO = PE.COD_PROCESSO
AND PRC.COD_ETAPA_ATUAL = PE.COD_ETAPA
AND PRC.COD_CICLO_ATUAL = PE.COD_CICLO
INNER JOIN FORMULARIO AS FRM
ON PRC.COD_FORM = FRM.COD_FORM
AND PRC.COD_VERSAO = FRM.COD_VERSAO
INNER JOIN ETAPA AS ETP
ON PRC.COD_FORM = ETP.COD_FORM
AND PRC.COD_VERSAO = ETP.COD_VERSAO
AND PRC.COD_ETAPA_ATUAL = ETP.COD_ETAPA
INNER JOIN USUARIO USU
ON USU.COD_USUARIO = PE.COD_USUARIO_ETAPA
WHERE PRC.IDE_FINALIZADO = 'A'
AND CONVERT(DATETIME, PRC.DAT_DATA) BETWEEN GETDATE()-154 AND GETDATE()-124
AND PRC.COD_FORM NOT IN (7, 12)
ORDER BY PRC.COD_FORM, PRC.COD_PROCESSO

SELECT 
	 PRC.COD_FORM
	,PRC.COD_PROCESSO
	,FRM.DES_TITULO
	,ETP.DES_ETAPA
	,PE.COD_USUARIO_ETAPA
	,USU.NOM_USUARIO
FROM PROCESSO AS PRC
INNER JOIN PROCESSO_ETAPA AS PE
ON PRC.COD_PROCESSO = PE.COD_PROCESSO
AND PRC.COD_ETAPA_ATUAL = PE.COD_ETAPA
AND PRC.COD_CICLO_ATUAL = PE.COD_CICLO
INNER JOIN FORMULARIO AS FRM
ON PRC.COD_FORM = FRM.COD_FORM
AND PRC.COD_VERSAO = FRM.COD_VERSAO
INNER JOIN ETAPA AS ETP
ON PRC.COD_FORM = ETP.COD_FORM
AND PRC.COD_VERSAO = ETP.COD_VERSAO
AND PRC.COD_ETAPA_ATUAL = ETP.COD_ETAPA
INNER JOIN USUARIO USU
ON USU.COD_USUARIO = PE.COD_USUARIO_ETAPA
WHERE PRC.IDE_FINALIZADO = 'A'
AND CONVERT(DATETIME, PRC.DAT_DATA) < GETDATE()-154
AND PRC.COD_FORM NOT IN (7, 12)
ORDER BY PRC.COD_FORM, PRC.COD_PROCESSO

-- CANCELA OS PROCESSOS VIA QUERY
UPDATE PRCETP
SET  IDE_STATUS = 'C'
	,DAT_FINALIZACAO = CONVERT(DATETIME,GETDATE())
FROM PROCESSO_ETAPA AS PRCETP
WHERE IDE_STATUS = 'A'
AND COD_PROCESSO IN ()

UPDATE PRC
SET IDE_FINALIZADO = 'C'
FROM PROCESSO AS PRC
WHERE IDE_FINALIZADO = 'A'
AND COD_PROCESSO IN ()

-- COLETA OS CODIGOS DOS USUARIOS GESTORES
SELECT COD_USU_GESTOR
FROM FORMULARIO
WHERE COD_FORM = 78
AND COD_VERSAO IN (
	SELECT MAX(COD_VERSAO)
	FROM FORMULARIO
	WHERE COD_FORM = 78
)

-- COLETA INFOS DO USUARIO ATIVO E Q TEM AUTENTICACAO PELO LDAP ATRAVES DO COD_USUARIO
SELECT 
	 COD_USUARIO
	,NOM_USUARIO
	,DES_LOGIN
	,IDE_ACESSO_ADM
	,IDE_USUARIO_INATIVO
	,DES_EMAIL
	,IDE_ACESSO_PESQ
	,IDE_ACESSO_ESTAT
	,IDE_ACESSO_MOD
	,COD_SUBSTITUTO
	,DATA_INI_FERIAS
	,DATA_FIM_FERIAS
	,IDE_ALTERAR_DADOS
	,COD_DEPTO
	,COD_LIDER
	,ACTIVED_AT
	,INACTIVED_AT
	,LAST_ACCESS_AT
	,IDE_AUTENTICA_TIPO
FROM USUARIO
WHERE COD_USUARIO IN (304,3117,1494,4,427,3)
AND IDE_USUARIO_INATIVO = 'N'
AND IDE_AUTENTICA_TIPO = 'LDAP'